### ISSUE TITLE
API calls all return object with top level results key

### ISSUE THREAD

**Issue by hatched** [juju/js-libjuju#19]
It seems like all api calls return an object with a top level results key which means that in order to use them you must access that key.

```JavaScript
const credentialList = await this._getCloudCredentialNames(props.userName, clouds).results;
const modelList = await this.props.modelManager.listModelSummaries().results;
```

It looks like we can modify this:

https://github.com/juju/js-libjuju/blob/428936e97201a50be9c0076dad898fe97e2909b9/templates/facade.js#L70
```JavaScript
      transform = resp => {
        let result;
        {{ method.result.generate_response('result', 'resp')|indent(8) }}
        return result;
      };
```

To instead be something like:
```JavaScript
      transform = resp => {
        let result;
        {{ method.result.generate_response('result', 'resp')|indent(8) }}
        return result.results || result;
      };
```

Through a quick glance at the codebase it looks like they always have `result.results` but it could be I just hadn't found the right api call that doesn't. In that case it would fall back to the whole response object.

**Comment by frankban** [comment]
This is very interesting. We have many calls returning a single top level field, in which cases we could generalize the logic you are proposing: `if there is only one top level field in the return type declaration, then return result[topLevelFieldName]`. Note that rather than just checking on the value, we should check on the type, so that we don't accidentally walk through a result key only because other keys are not defined for that specific response.
Unfortunately, there is a big downside of this whole proposal: even if it makes the result prettier, what happen when juju introduces another field in that response? From the Juju pov, that change only extends the response, so it's not backward incompatible, so they might decide not to bump the facade version number. But it would be incompatible for the client.
